apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-python-ssh
  labels:
    app: ubuntu-python-ssh
spec:
  containers:
    - name: pycharm-dev
      image: mkhlfrlv/ubuntu-sshd-dev:1.0
      imagePullPolicy: Always
      resources:
        requests: 
          memory: "6144Mi"
          cpu: "1"
        limits:
          memory: "8192Mi"
          cpu: "2"
      ports:
        - containerPort: 22
      securityContext:
        privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-ssh-service
spec:
  type: NodePort
  selector:
    app: ubuntu-python-ssh
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022
